name: Run tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'gradle'
    - uses: allure-framework/setup-allurectl@v1
      with: 
        allure-endpoint: https://testing.qatools.cloud/
        allure-token: 78348dba-d0b7-4778-b165-288557c23a3b
        allure-project-id: 1278
    - run: allurect watch -- ./gradlew clean test
      env: 
        ALLURE_RESULTS: build/allure-results
